### PR TITLE
#2 doc comments for each function in pystring object and new function…

### PR DESCRIPTION
**Pull request by achengli**
Hello @liaozhaoyan 

I did some additions:
- New doc comments for each function in pystring.
- New function called **with** which use a file giving an abstraction to the programmer with the file descriptor.

### CODE REVIEW

**Comment by liaozhaoyan** [comment]
Very good, but with a slightly strange point: with is an io processing function, which has little to do with string processing, is it appropriate to put it in pystring?

**Comment by achengli** [comment]
You're right!

"with" function is not a string processing function. I modified it focusing the function on the file content and not just on the file descriptor; however if it doesn't fit with **pystring**, I will remove it and I will just send the doc comments additions .

**Comment by liaozhaoyan** [comment]
Then, if you can add a test case for with function to test.lua, it will be perfect

**Comment by achengli** [comment]
Ready! I have given an example of use with verification in the modular tests.

**Comment by liaozhaoyan** [comment]
hey, I have adjusted the order of parameters of the with function and added a default function to the callback function, which can make the with function more convenient to use. At the same time, the calling method of the entire library has undergone major changes, from pystring:split->pystring.split, which can save one parameter. The initial consideration was to implement it as a class, but now I think it is more direct to use function calling.

**Comment by achengli** [comment]
That's awesome. These are very good enhancements over the **with** function.

About the new paradigm, I think also that is better to implement functions directly as functions and not as class methods since it is more natural and convenient for the common Lua workflow. I guess Lua was designed for automation tasks having a significant low memory and resources consumption, and that's because functional programming is better over OOP in this situation.

Thank you for the new contributions!. I going to take a look to the code and test it a few days later.

Have a nice day @liaozhaoyan !

**Pull request merged**
